### ISSUE TITLE
User won't be able to deallocate if the asset is later added to purgatory

### ISSUE THREAD

**Issue by trizin** [oceanprotocol/df-py#314]
User won't be able to deallocate if the asset is later added to purgatory. We should provide assets in purgatory in nftinfo csv and mark them.

@AnaLoznianu:
What happens if I curate a certain data asset that is later put to purgatory? will the asset still be visible on the df web? Can I remove my allocation?

**Comment by idiom-bytes** [comment]
I wonder if we should reflect this in the FE somehow?

Candidate solutions:
A) Assets in purgatory should perhaps have an icon/highlight to let the user know that asset is no longer viable
B) Instead of having assets from purgatory inside nftinfo.csv, have a purgatory.csv or let's get the info on FE directly from there. Let user know they have assets in purgatory, and create a "Reset Allocations" button that enables them to reset it to 100% and start again.
C) Same as B. But only sets the Allocations on the purgatory items to 0, and regains that allocation % to distribute again.

**Comment by idiom-bytes** [comment]
Me and Trizin voted for Cand B.

I have proposed we implement it as part of an update to the explorer.
This is discussed further in ticket => https://github.com/oceanprotocol/df-web/issues/297

![Screenshot from 2022-09-30 13-31-46.png](https://images.zenhubusercontent.com/601eeb154030993736fc619e/de557a80-021d-4a4d-bdba-db46318bbae2)

**Comment by KatunaNorbert** [comment]
I would vote for Cand C, but I would still like to have all assets inside nftInfo instead of having another endpoint to get those assets.

**Comment by KatunaNorbert** [comment]
Yes, that should be enough as long as we also have the allocations for those assets from subgraph

**Comment by idiom-bytes** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VE--DF-60ddbf267dd0b500137f3c3d/issues/oceanprotocol/df-py/314?planning-poker) with Zenhub @KatunaNorbert

**Comment by idiom-bytes** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VE--DF-60ddbf267dd0b500137f3c3d/issues/oceanprotocol/df-py/314?planning-poker) with Zenhub @trizin
