### ISSUE TITLE
Add passive rewards amount to vebals.csv

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/df-py#443]
Every time we compute vebals, we can compute amount of passive rewards received by an user for a DF round

Let's add a column, called "amt"  (to keep existing naming, as rewardsInfo is uses amt as well).

And here is how to calculate it:
  - timestamp = beginning of a DF round (for current round: timestamp = current_unix_timestamp / 604800* 604800
  - total_passive_OCEAN= veFeeDistributor.tokens_per_week(timestamp)
  - total_ve_supply = veFeeDistributor.ve_supply(timestamp)
  - OCEAN_per_veOCEAN=total_passive_OCEAN/ total_ve_supply
  - for each user:
  - - user_passive_OCEAN= veFeeDistributor.ve_for_at(user_address,timestamp) * OCEAN_per_veOCEAN

What is "user_passive_OCEAN" ?   amount of Ocean tokens received by a user for passive staking, during that round
Why do this?  So we can store and calculate history of passive rewards

APY calculation in df-web:   easy, since we have user_locked_balance and amount of Ocean received as reward

This introduces another question.  Which veOcean_balance should we use across ve+df ?
 - veFeeDistributor records veOcean_balance per user at the beginning of the round  (see veFeeDistributor.ve_for_at(timestamp,user) )
 - df-py veBals computes an average using 50 snapshots
 
 veFeeDistributor.ve_for_at  >  df-py vebal   (because veOcean balance diminishes during those 50 snapshots)

(This works in tandem with https://github.com/oceanprotocol/df-sql/issues/29), we need to merge them in the same time

**Comment by trentmc** [comment]
It's currently hard to comment on the "heart of the issue" because the variable naming makes it hard to reason about:
-  `ocean_rewarded_per_week` is not really denominated in ocean tokens, since it was computed with veOCEAN in the ratio. And its current label doesn't distinguish well from 'tokens_per_per_week'. 
- 'tokens_per_week' doesn't really indicate OCEAN. 
- 'amt' is obviously ambiguous.

A small trick: You don't need to have "per_week" in the variable labels since everything is for the week.

Then, suggestions:
- `tokens_per_week` -> `total_passive_OCEAN`
- 'ocean_rewarded_per_week' -> 'OCEAN_per_veOCEAN`
- `amt` -> 'user_passive_OCEAN`

Fixing this in the description above will help to comment on the heart of the issue. Thank you.

**Comment by trentmc** [comment]
> This introduces another question. Which veOcean_balance should we use across ve+df ?
> - veFeeDistributor records veOcean_balance per user at the beginning of the round (see veFeeDistributor.ve_for_at(timestamp,user) )
> - df-py veBals computes an average using 50 snapshots

Here's one solution: use df-py to compute at the beginning of the round:
- have a separate call to `dftool vebals ST FIN NSAMP CSV_DIR CHAINID`
- where ST = FIN = timestamp. Then it will be just 1 snapshot at that time
- and store the resulting csv separately from the results

**Comment by alexcos20** [comment]
let's have another command:
```dftool calculate_passive DATE```

where DATE = timestamp that gets rounded to df week start

It will generate a csv that has the following columns:
LP_addr   = user address
veBalance  = veBalance (taken from veFeeDistributor.ve_for_at(user_address,timestamp)
amt  = reward , computed using above scenario
token = reward token
