### ISSUE TITLE
Migrate CI to 'pip install .'

### ISSUE THREAD

**Issue by trizin** [oceanprotocol/df-py#608]
Migrate CI workflows to use 'pip install .' instead of requirements txt.

**Comment by calina-c** [comment]
I investigated this and it seems to be moot. I initially agreed it was necessary, but it turns out it is not. We needed that in Dockerfile to retrieve the "rest" of the library (we were only copying requirements.txt and not the library itself). But the GithubActions use the checkout step, which gets us the full lib and the requirements.txt will correctly point to setup.py. We see this since the flows and CIs are still working.

I will close this.
