### ISSUE TITLE
Update modules to use block time instead of local time

### ISSUE THREAD

**Issue by trizin** [oceanprotocol/df-py#629]
Remove usages of local/machine time and replace them with chain time.

**Comment by calina-c** [comment]
Adding more context here and expanding the scope a bit. Currently we can not run tests in any given order, meaning they are interdependent somehow. In order to advance things, we added a string ordering of test modules in the test GitHub Action. However, we commented out the blocktime tests, which only work if ran before any advances to the chain.

I think this issue should include:
- removing dependencies between tests, allow for any ordering, i.e. simply run `pytest util` instead of `pytest util/volume util/challenge [...]`. -> this is brittle because if new modules are added someone might forget to add them to the flow.
- unskipping and fixing blocktime tests, where usages of chain time should be employed.
